### ISSUE TITLE
illegal multibyte sequence

### ISSUE THREAD

**Issue by Achillesy** [gift-surg/NSoL#1]
If you run "pip install NSoL" in windows, you will get:

Collecting NSoL
  Using cached NSoL-0.1.14.tar.gz (64 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xxx\miniconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Temp\\pip-install-8ricpyix\\nsol_d2abd9cbbe344f16824d3d270758c984\\setup.py'"'"'; __file__='"'"'C:\\Temp\\pip-install-8ricpyix\\nsol_d2abd9cbbe344f16824d3d270758c984\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Temp\pip-pip-egg-info-libj0zqz'
         cwd: C:\Temp\pip-install-8ricpyix\nsol_d2abd9cbbe344f16824d3d270758c984\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Temp\pip-install-8ricpyix\nsol_d2abd9cbbe344f16824d3d270758c984\setup.py", line 17, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 9309: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by renbem** [comment]
Hi Achillesy,
Thanks for your comment. As mentioned in the [Installation](https://github.com/gift-surg/NSoL#installation) section, NSoL was developed and tested only in OSX/Ubuntu.

**Comment by Achillesy** [comment]
Thank you.
I am trying to install MONAIfbs. For this reason, I must install ubuntu first.
I'm sorry to hear this news, Ouch. ;p

**Comment by renbem** [comment]
1. MONAIfbs is not managed by me
2. NSoL (and all gift-surg software for that matter) is research software
3. Since I have seen your [comment for NiftyMIC](https://github.com/gift-surg/NiftyMIC/issues/14): All associated software (including NSoL and MONAIfbs) is available as part of a virtual machine and docker image to ensure straightforward use on any operating system
